name: CI pipeline for Main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging 🚀
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MSERVER_HOST }}
          username: ${{ secrets.MSERVER_SSH_USER }}
          key: ${{ secrets.MSERVER_SSH_KEY }}
          script: |
            cd ~/cyberoni-test
            git fetch && git reset --hard origin/main
            docker-compose up --build &